//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class AnimationUtils
{

		public static IEnumerator waitToEnd (Animation animation)
		{
				do {
						yield return null;
				} while (animation.isPlaying);
		}

		public static IEnumerator wait (int seconds)
		{
				yield return new WaitForSeconds (seconds);
		}

		public static bool animatorStateEquals (Animator animator, AnimationEnum state)
		{
				return animator.GetCurrentAnimatorStateInfo (0).nameHash == Animator.StringToHash (state.name);
		}
}

