//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public sealed class AnimationEnum
{

		public readonly String name;

		public static readonly AnimationEnum HERO_IDLE = new AnimationEnum ("HeroLayer.idle");
		public static readonly AnimationEnum HERO_RUNNING = new AnimationEnum ("HeroLayer.running");
		public static readonly AnimationEnum HERO_ROLLING = new AnimationEnum ("HeroLayer.rolling");
		public static readonly AnimationEnum HERO_JUMPING = new AnimationEnum ("HeroLayer.jumping");

		public static readonly AnimationEnum ENEMY_IDLE = new AnimationEnum ("Base Layer.idle");
		public static readonly AnimationEnum ENEMY_RUN = new AnimationEnum ("Base Layer.run");
		public static readonly AnimationEnum ENEMY_ATTACK = new AnimationEnum ("Base Layer.attack");

		public static readonly AnimationEnum DIALOGBOX_HIDDEN = new AnimationEnum ("Base Layer.hidden");
		public static readonly AnimationEnum DIALOGBOX_VISIBLE = new AnimationEnum ("Base Layer.visible");
		public static readonly AnimationEnum DIALOGBOX_FADEIN = new AnimationEnum ("Base Layer.fadeIn");

		public AnimationEnum (String name)
		{
				this.name = name;
		}

}

