//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class LayerEnum
{		
		public static LayerEnum GROUND = new LayerEnum (8);
		public static LayerEnum Ladder = new LayerEnum (9);
		public static LayerEnum BLadderGround = new LayerEnum (10);
		public static LayerEnum TANGIBLE = new LayerEnum (11);
		public static LayerEnum TLadderGround = new LayerEnum (12);
		public static LayerEnum NPC = new LayerEnum (12);

		public int number;

		public LayerEnum (int number)
		{
				this.number = number;
		}
}

