//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
public class TagEnum
{

		public readonly string name;

		public static readonly TagEnum LADDER = new TagEnum ("ladder");
		public static readonly TagEnum GROUND = new TagEnum ("ground");

		public TagEnum (string name)
		{
				this.name = name;
		}
}
