//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Rune
{

		public enum Elemental
		{
				FIRE,
				THUNDER,
				LIGHT,
				DARK
		}

		private Elemental elemental;


		public Rune (Elemental elemental)
		{
				this.elemental = elemental;
		}
}

