//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class Vision : MonoBehaviour
{

		private int width { get; set; }
		private int height { get; set; }

		private bool aggro;

		public Vision ()
		{
				this.aggro = false;
		}

		public Vision (int width, int height, int weaponWidth, int weaponHeight)
		{
				this.width = width;
				this.height = height;
		}

		public void Start ()
		{
		}

		public void OnTriggerEnter2D (Collider2D coll)
		{
				if (coll.gameObject.tag == TagEnum.HERO.name) {
						this.aggro = true;
				}
		}

		public void OnTriggerExit2D (Collider2D coll)
		{
				if (coll.gameObject.tag == TagEnum.HERO.name) {
						this.aggro = false;
				}
		}
	
		public bool isAggro ()
		{
				return this.aggro;
		}

}

