//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class DialogBox : MonoBehaviour
{

	private List<String> dialogs;

	public SpriteRenderer SpriteRenderer;

	public DialogBox ()
	{
	}

	public void Start ()
	{
		this.SpriteRenderer.enabled = false;
	}

	public DialogBox (List<String> dialogs)
	{
		this.dialogs = dialogs;
	}

	public String getDialog (int index)
	{
		return this.dialogs [index];
	}

	public void enable ()
	{
		this.SpriteRenderer.enabled = true;
	}

	public void disable ()
	{
		this.SpriteRenderer.enabled = false;
	}
}

