//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class INPC : MonoBehaviour
{

	private bool canSpeak;

	public DialogBox dialogBox;

	public INPC ()
	{
		this.canSpeak = true;
	}

	public bool hasSomethingToSay ()
	{
		return this.canSpeak;
	}

	public void OnTriggerEnter2D (Collider2D coll)
	{
		if (this.canSpeak && coll.gameObject.tag == TagEnum.HERO.name) {
			this.dialogBox.enable ();
		}
	}

	public void OnTriggerExit2D (Collider2D coll)
	{
		if (this.canSpeak) {
			this.dialogBox.disable ();
		}
	}
}

