//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.33440
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public sealed class AnimationEnum
{

		private String name;

		public static readonly AnimationEnum IDLE = new AnimationEnum ("idle");
		public static readonly AnimationEnum RUNNING = new AnimationEnum ("running");
		public static readonly AnimationEnum ROLLING = new AnimationEnum ("rolling");

		public AnimationEnum (String name)
		{
				this.name = name;
		}

		public String getName ()
		{
				return this.name;
		}

}

